### ISSUE TITLE
Type 7 : GeometryCollection

### ISSUE THREAD

**Issue by pramsey** [TWKB/Specification#13]
I'm not understanding this one.

It says we have ngeoms, and then:

    For each geometry {<br>
    * varInt describing type and ndim  of subgeometry<br>
    * a geometry of the specified type without ID<br>
    }

But each sub-geometry should already have a type, so that seems duplicative to me. Also, why have a collection that disallows individual ids (7) and one that requires them (the upcoming 'heterogeneous group 21') when they are structurally basically the same thing?

**Comment by nicklasaven** [comment]
In the spec I have defined the type-information not as part of the type. 

The client is blank, doesn't know anything -> reads the type information. 

Then it starts reading that type according to the spec.

 Does that make sense?

The last thing about type 7 vs heterogeneous geometry group:

This I have found quite complex. The problem is to find the simplest rules to handle all cases. 
The cases is at least thos for differnt collection/group variants:

1) ordinary geometry collection like in PostGIS, just a bunch of geometries, optionally with a common ID

2) A bunch of single geometries with individual ID:s

3) a bunch of geometry collections (type 7) where each collection have their ID

And when the client starts to read it must know if it is an ID-value that it is reading or if it is the next part of some geometry or collection. 

I haven't clearly seen the best option for this, that is why aIl started with all those group types. But I think this homogeneous/heterogeneous approach to groups is more in the right direction.

For a while I considered rethinking the whole type system. Describing the type by some bits. 
In general I think it is important to look at the problem from both client and back end perspective to find the best solution.
This idea is mostly from client perspective.
If we use 5 bits for type description if could look lke this:
*   1 bit: telling if what is coming have multiple objects. If so the client will find a varint with n_geoms starting at next byte.

*   1 bit telling if what is coming have individual ID:s. If so the first value after n_geoms is ID (If there is an ID at "this level" that is before the type byte we are reading now)

*   1 bit: If it is a group/collection that is coming, then, "Is is heterogeneous?" If so, after ID comes a new type byte again. 

*   2 bits, this is in reality not used if previous bit says heterogeneous. But here comes info about point/line/polygon (and possible arc as last option) 

This way the client can just read on and the bits tells what to expect next. No type conversion tables is needed, more than for point/line/polygon.

Example:
linestring and point with individual id, then the 5 bit type description looks like:
1)   11100

2)   n_geoms (first bit says)

3)   ID (second bit says)

4)   new type byte (third bit says)
      00020 (if line is n at the end Note that ID for the linestring is already read so 0 at ID position)

5)   n_points and coordinates for linestring

6)   ID (for the point)

7)   new type byte 
      00001 (if point is nr 1. )

8)  Coordinate for point


If last point instead would have been a multipoint the type byte at 7 would instead have been:
10001

followed by 

n_geoms

and then 

coordinates for multipoint


  
I don't know, maybe to wild thinking, but I find that refreashing somoetimes even if it doesn't lead anywhere
